// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Annotation struct {
	ID            string `json:"id"`
	Value         string `json:"value"`
	EditableValue string `json:"editable_value"`
	CreatedBy     string `json:"created_by"`
	CreatedAt     string `json:"created_at"`
	Tag           string `json:"tag"`
	Version       int    `json:"version"`
	EntryID       string `json:"entry_id"`
	Ontology      string `json:"ontology"`
	Rank          *int   `json:"rank"`
	IsObsolete    *bool  `json:"is_obsolete"`
}

type AnnotationListWithCursor struct {
	Annotations    []Annotation `json:"annotations"`
	NextCursor     string       `json:"nextCursor"`
	PreviousCursor string       `json:"previousCursor"`
	Limit          *int         `json:"limit"`
	TotalCount     int          `json:"totalCount"`
}

type Author struct {
	LastName  *string `json:"last_name"`
	FirstName *string `json:"first_name"`
	Initials  *string `json:"initials"`
	Rank      *string `json:"rank"`
}

type CreateAnnotationInput struct {
	Value         string `json:"value"`
	EditableValue string `json:"editable_value"`
	CreatedBy     string `json:"created_by"`
	Tag           string `json:"tag"`
	EntryID       string `json:"entry_id"`
	Ontology      string `json:"ontology"`
	Rank          *int   `json:"rank"`
}

type CreateAuthorInput struct {
	LastName  *string `json:"last_name"`
	FirstName *string `json:"first_name"`
	Initials  *string `json:"initials"`
	Rank      *string `json:"rank"`
}

type CreateOrderInput struct {
	Courier          string    `json:"courier"`
	CourerAccount    string    `json:"courer_account"`
	Comments         *string   `json:"comments"`
	Payment          string    `json:"payment"`
	PurchaseOrderNum string    `json:"purchase_order_num"`
	Status           string    `json:"status"`
	Consumer         string    `json:"consumer"`
	Payer            string    `json:"payer"`
	Purchaser        string    `json:"purchaser"`
	Items            []*string `json:"Items"`
}

type CreatePermissionInput struct {
	Permission  string `json:"permission"`
	Description string `json:"description"`
	Resource    string `json:"resource"`
}

type CreatePlasmidInput struct {
	CreatedBy         string                        `json:"created_by"`
	UpdatedBy         string                        `json:"updated_by"`
	Summary           *string                       `json:"summary"`
	EditableSummary   *string                       `json:"editable_summary"`
	Depositor         *string                       `json:"depositor"`
	Genes             []*string                     `json:"genes"`
	Dbxrefs           []*string                     `json:"dbxrefs"`
	Publications      []*string                     `json:"publications"`
	PlasmidProperties *CreatePlasmidPropertiesInput `json:"plasmid_properties"`
}

type CreatePlasmidPropertiesInput struct {
	ImageMap *string `json:"image_map"`
	Sequence *string `json:"sequence"`
}

type CreatePublicationInput struct {
	Doi      *string              `json:"doi"`
	Title    *string              `json:"title"`
	Abstract *string              `json:"abstract"`
	Journal  *string              `json:"journal"`
	PubDate  *string              `json:"pub_date"`
	Volume   *string              `json:"volume"`
	Pages    *string              `json:"pages"`
	Issn     *string              `json:"issn"`
	PubType  *string              `json:"pub_type"`
	Source   *string              `json:"source"`
	Issue    *string              `json:"issue"`
	Status   *string              `json:"status"`
	Authors  []*CreateAuthorInput `json:"authors"`
}

type CreateRoleInput struct {
	Role        string `json:"role"`
	Description string `json:"description"`
}

type CreateStrainInput struct {
	CreatedBy        string                      `json:"created_by"`
	UpdatedBy        string                      `json:"updated_by"`
	Summary          *string                     `json:"summary"`
	EditableSummary  *string                     `json:"editable_summary"`
	Depositor        *string                     `json:"depositor"`
	Genes            []*string                   `json:"genes"`
	Dbxrefs          []*string                   `json:"dbxrefs"`
	Publications     []*string                   `json:"publications"`
	StrainProperties CreateStrainPropertiesInput `json:"strain_properties"`
}

type CreateStrainPropertiesInput struct {
	SystematicName string    `json:"systematic_name"`
	Descriptor     string    `json:"descriptor"`
	Species        string    `json:"species"`
	Plasmid        *string   `json:"plasmid"`
	Parents        []*string `json:"parents"`
	Names          []*string `json:"names"`
}

type CreateUserInput struct {
	FirstName     string  `json:"first_name"`
	LastName      string  `json:"last_name"`
	Email         string  `json:"email"`
	Organization  *string `json:"organization"`
	GroupName     *string `json:"group_name"`
	FirstAddress  *string `json:"first_address"`
	SecondAddress *string `json:"second_address"`
	City          *string `json:"city"`
	State         *string `json:"state"`
	Zipcode       *string `json:"zipcode"`
	Country       *string `json:"country"`
	Phone         *string `json:"phone"`
	IsActive      bool    `json:"is_active"`
}

type DeleteItem struct {
	Success bool `json:"success"`
}

type Order struct {
	ID               string    `json:"id"`
	CreatedAt        string    `json:"created_at"`
	UpdatedAt        string    `json:"updated_at"`
	Courier          *string   `json:"courier"`
	CourerAccount    *string   `json:"courer_account"`
	Comments         *string   `json:"comments"`
	Payment          *string   `json:"payment"`
	PurchaseOrderNum *string   `json:"purchase_order_num"`
	Status           *string   `json:"status"`
	Consumer         *string   `json:"consumer"`
	Payer            *string   `json:"payer"`
	Purchaser        *string   `json:"purchaser"`
	Items            []*string `json:"Items"`
}

type OrderListWithCursor struct {
	Orders         []Order `json:"orders"`
	NextCursor     string  `json:"nextCursor"`
	PreviousCursor string  `json:"previousCursor"`
	Limit          *int    `json:"limit"`
	TotalCount     int     `json:"totalCount"`
}

type Permission struct {
	ID          string  `json:"id"`
	Permission  string  `json:"permission"`
	Description string  `json:"description"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
	Resource    *string `json:"resource"`
}

type PlasmidProperties struct {
	ImageMap *string `json:"image_map"`
	Sequence *string `json:"sequence"`
}

type Publication struct {
	ID       string    `json:"id"`
	Doi      *string   `json:"doi"`
	Title    *string   `json:"title"`
	Abstract *string   `json:"abstract"`
	Journal  *string   `json:"journal"`
	PubDate  *string   `json:"pub_date"`
	Volume   *string   `json:"volume"`
	Pages    *string   `json:"pages"`
	Issn     *string   `json:"issn"`
	PubType  *string   `json:"pub_type"`
	Source   *string   `json:"source"`
	Issue    *string   `json:"issue"`
	Status   *string   `json:"status"`
	Authors  []*Author `json:"authors"`
}

type PublicationListWithCursor struct {
	Publications   []Publication `json:"publications"`
	NextCursor     string        `json:"nextCursor"`
	PreviousCursor string        `json:"previousCursor"`
	Limit          *int          `json:"limit"`
	TotalCount     int           `json:"totalCount"`
}

type Role struct {
	ID          string       `json:"id"`
	Role        string       `json:"role"`
	Description string       `json:"description"`
	CreatedAt   string       `json:"created_at"`
	UpdatedAt   string       `json:"updated_at"`
	Permissions []Permission `json:"permissions"`
}

type Stock struct {
	ID                string             `json:"id"`
	CreatedAt         string             `json:"created_at"`
	UpdatedAt         string             `json:"updated_at"`
	CreatedBy         string             `json:"created_by"`
	UpdatedBy         string             `json:"updated_by"`
	Summary           *string            `json:"summary"`
	EditableSummary   *string            `json:"editable_summary"`
	Depositor         *string            `json:"depositor"`
	Genes             []*string          `json:"genes"`
	Dbxrefs           []*string          `json:"dbxrefs"`
	Publications      []*string          `json:"publications"`
	StrainProperties  *StrainProperties  `json:"strain_properties"`
	PlasmidProperties *PlasmidProperties `json:"plasmid_properties"`
}

type StockListWithCursor struct {
	Stocks         []Stock `json:"stocks"`
	NextCursor     string  `json:"nextCursor"`
	PreviousCursor string  `json:"previousCursor"`
	Limit          *int    `json:"limit"`
	TotalCount     int     `json:"totalCount"`
}

type StrainProperties struct {
	SystematicName string    `json:"systematic_name"`
	Descriptor     string    `json:"descriptor"`
	Species        string    `json:"species"`
	Plasmid        *string   `json:"plasmid"`
	Parents        []*string `json:"parents"`
	Names          []*string `json:"names"`
}

type UpdateAnnotationInput struct {
	Value         string `json:"value"`
	EditableValue string `json:"editable_value"`
	CreatedBy     string `json:"created_by"`
}

type UpdateAuthorInput struct {
	LastName  *string `json:"last_name"`
	FirstName *string `json:"first_name"`
	Initials  *string `json:"initials"`
	Rank      *string `json:"rank"`
}

type UpdateOrderInput struct {
	Courier          *string   `json:"courier"`
	CourierAccount   *string   `json:"courier_account"`
	Comments         *string   `json:"comments"`
	Payment          *string   `json:"payment"`
	PurchaseOrderNum *string   `json:"purchase_order_num"`
	Status           *string   `json:"status"`
	Items            []*string `json:"Items"`
}

type UpdatePermissionInput struct {
	Permission  string `json:"permission"`
	Description string `json:"description"`
	Resource    string `json:"resource"`
}

type UpdatePlasmidPropertiesInput struct {
	ImageMap *string `json:"image_map"`
	Sequence *string `json:"sequence"`
}

type UpdatePublicationInput struct {
	PubDate *string              `json:"pub_date"`
	Volume  *string              `json:"volume"`
	Pages   *string              `json:"pages"`
	PubType *string              `json:"pub_type"`
	Source  *string              `json:"source"`
	Status  *string              `json:"status"`
	Authors []*UpdateAuthorInput `json:"authors"`
}

type UpdateRoleInput struct {
	Role        string `json:"role"`
	Description string `json:"description"`
}

type UpdateStockInput struct {
	UpdatedBy         string                        `json:"updated_by"`
	Summary           *string                       `json:"summary"`
	EditableSummary   *string                       `json:"editable_summary"`
	Depositor         *string                       `json:"depositor"`
	Genes             []*string                     `json:"genes"`
	Dbxrefs           []*string                     `json:"dbxrefs"`
	Publications      []*string                     `json:"publications"`
	StrainProperties  *UpdateStrainPropertiesInput  `json:"strain_properties"`
	PlasmidProperties *UpdatePlasmidPropertiesInput `json:"plasmid_properties"`
}

type UpdateStrainPropertiesInput struct {
	SystematicName *string   `json:"systematic_name"`
	Descriptor     *string   `json:"descriptor"`
	Species        *string   `json:"species"`
	Plasmid        *string   `json:"plasmid"`
	Parents        []*string `json:"parents"`
	Names          []*string `json:"names"`
}

type UpdateUserInput struct {
	FirstName     *string `json:"first_name"`
	LastName      *string `json:"last_name"`
	Organization  *string `json:"organization"`
	GroupName     *string `json:"group_name"`
	FirstAddress  *string `json:"first_address"`
	SecondAddress *string `json:"second_address"`
	City          *string `json:"city"`
	State         *string `json:"state"`
	Zipcode       *string `json:"zipcode"`
	Country       *string `json:"country"`
	Phone         *string `json:"phone"`
	IsActive      *bool   `json:"is_active"`
}

type User struct {
	ID            string  `json:"id"`
	FirstName     string  `json:"first_name"`
	LastName      string  `json:"last_name"`
	Email         string  `json:"email"`
	Organization  *string `json:"organization"`
	GroupName     *string `json:"group_name"`
	FirstAddress  *string `json:"first_address"`
	SecondAddress *string `json:"second_address"`
	City          *string `json:"city"`
	State         *string `json:"state"`
	Zipcode       *string `json:"zipcode"`
	Country       *string `json:"country"`
	Phone         *string `json:"phone"`
	IsActive      bool    `json:"is_active"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     string  `json:"updated_at"`
	Roles         []Role  `json:"roles"`
}

type UserListWithCursor struct {
	Users          []User `json:"users"`
	NextCursor     string `json:"nextCursor"`
	PreviousCursor string `json:"previousCursor"`
	Limit          *int   `json:"limit"`
	TotalCount     int    `json:"totalCount"`
}
