// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"github.com/dictyBase/go-genproto/dictybaseapis/order"
	"github.com/dictyBase/go-genproto/dictybaseapis/user"
)

type CreateOrderInput struct {
	Courier          string    `json:"courier"`
	CourerAccount    string    `json:"courer_account"`
	Comments         *string   `json:"comments"`
	Payment          string    `json:"payment"`
	PurchaseOrderNum string    `json:"purchase_order_num"`
	Status           string    `json:"status"`
	Consumer         string    `json:"consumer"`
	Payer            string    `json:"payer"`
	Purchaser        string    `json:"purchaser"`
	Items            []*string `json:"Items"`
}

type CreatePermissionInput struct {
	Permission  string `json:"permission"`
	Description string `json:"description"`
	Resource    string `json:"resource"`
}

type CreateRoleInput struct {
	Role        string `json:"role"`
	Description string `json:"description"`
}

type CreateUserInput struct {
	FirstName     string  `json:"first_name"`
	LastName      string  `json:"last_name"`
	Email         string  `json:"email"`
	Organization  *string `json:"organization"`
	GroupName     *string `json:"group_name"`
	FirstAddress  *string `json:"first_address"`
	SecondAddress *string `json:"second_address"`
	City          *string `json:"city"`
	State         *string `json:"state"`
	Zipcode       *string `json:"zipcode"`
	Country       *string `json:"country"`
	Phone         *string `json:"phone"`
	IsActive      bool    `json:"is_active"`
}

type DeleteItem struct {
	Success bool `json:"success"`
}

type OrderListWithCursor struct {
	Orders         []order.Order `json:"orders"`
	NextCursor     string        `json:"nextCursor"`
	PreviousCursor string        `json:"previousCursor"`
	Limit          *int          `json:"limit"`
	TotalCount     int           `json:"totalCount"`
}

type UpdateOrderInput struct {
	Courier          *string   `json:"courier"`
	CourierAccount   *string   `json:"courier_account"`
	Comments         *string   `json:"comments"`
	Payment          *string   `json:"payment"`
	PurchaseOrderNum *string   `json:"purchase_order_num"`
	Status           *string   `json:"status"`
	Items            []*string `json:"Items"`
}

type UpdatePermissionInput struct {
	Permission  string `json:"permission"`
	Description string `json:"description"`
	Resource    string `json:"resource"`
}

type UpdateRoleInput struct {
	Role        string `json:"role"`
	Description string `json:"description"`
}

type UpdateUserInput struct {
	FirstName     *string `json:"first_name"`
	LastName      *string `json:"last_name"`
	Organization  *string `json:"organization"`
	GroupName     *string `json:"group_name"`
	FirstAddress  *string `json:"first_address"`
	SecondAddress *string `json:"second_address"`
	City          *string `json:"city"`
	State         *string `json:"state"`
	Zipcode       *string `json:"zipcode"`
	Country       *string `json:"country"`
	Phone         *string `json:"phone"`
	IsActive      *bool   `json:"is_active"`
}

type UserList struct {
	Users      []user.User `json:"users"`
	PageNum    *string     `json:"pageNum"`
	PageSize   *string     `json:"pageSize"`
	TotalCount int         `json:"totalCount"`
}
